# Generated by Django 4.1.3 on 2022-11-20 14:05

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hotel_meta_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='history',
            field=models.JSONField(blank=True, default=main.models.get_default_something, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='meta_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='main.metahotel'),
        ),
    ]
